"""
Main Execution Loop for Autonomous Tractor Simulation.
Integrates GPS, Path Generation, and Control Logic.
"""

import time
import math
import sys
import os
import csv

# Ensure src is in path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from src import config
from src.gps_simulator import GPSSimulator
from src.gps_reader import GPSReader
from src.path_follower import PurePursuitController

def load_path_from_csv(file_path):
    path = []
    with open(file_path, "r") as f:
        reader = csv.reader(f)
        next(reader)
        for row in reader:
            path.append((float(row[0]), float(row[1])))
    return path

def main():
    print("==================================================")
    print("   AUTONOMOUS TRACTOR GUIDANCE SYSTEM (SIMULATION)")
    print("==================================================")

    USE_SIMULATION = True

    os.makedirs("data", exist_ok=True)

    # 1. Initialize GPS
    if USE_SIMULATION:
        print("[INIT] Starting GPS Simulator...")
        gps = GPSSimulator(start_lat=config.REF_LAT,
                           start_lon=config.REF_LON,
                           start_heading=config.INITIAL_HEADING)
    else:
        print("[INIT] Connecting to Real GPS...")
        gps = GPSReader()

    # 2. Load Path from CSV (Generated by path_generator.py)
    print("[INIT] Loading Field Coverage Path...")
    path_file = os.path.join("data", "waypoints.csv")

    if not os.path.exists(path_file):
        print("[ERROR] Path file not found. Run path_generator.py first!")
        return

    path_local = load_path_from_csv(path_file)

    if not path_local:
        print("[ERROR] No path loaded!")
        return

    # 3. Initialize Controller
    controller = PurePursuitController()

    print(f"[READY] Path loaded with {len(path_local)} waypoints.")
    print("[READY] Starting Control Loop... Press Ctrl+C to stop.")
    time.sleep(1)

    # 4. Control Loop
    try:
        start_time = time.time()
        traj = []

        with open("data/telemetry.csv", "w", newline="") as tel_f:
            tel_w = csv.writer(tel_f)
            tel_w.writerow(["time", "x", "y", "heading_deg", "steer_deg", "xte", "target_idx"])

            while True:
                loop_start = time.time()

                # --- READ SENSORS ---
                state = gps.get_state()

                # --- CONTROL ---
                steer_rad, xte, target_idx = controller.get_steering_control(state, path_local)
                steer_deg = math.degrees(steer_rad)

                # --- SIMULATION UPDATE ---
                gps.update(steer_rad, config.DT)

                # --- LOGGING ---
                elapsed = time.time() - start_time
                print(f"Time: {elapsed:5.1f}s | "
                      f"Pos: ({state['x']:6.1f}, {state['y']:6.1f})m | "
                      f"Head: {state['heading']:5.1f}° | "
                      f"XTE: {xte:5.2f}m | "
                      f"Steer: {steer_deg:5.1f}° | "
                      f"Idx: {target_idx}/{len(path_local)}")

                tel_w.writerow([f"{elapsed:.2f}",
                                f"{state['x']:.3f}",
                                f"{state['y']:.3f}",
                                f"{state['heading']:.2f}",
                                f"{steer_deg:.2f}",
                                f"{xte:.3f}",
                                target_idx])

                traj.append((state['x'], state['y']))

                # End condition
                dist_to_end = math.hypot(state['x'] - path_local[-1][0],
                                         state['y'] - path_local[-1][1])
                if dist_to_end < 1.0 and target_idx >= len(path_local) - 5:
                    print("\n[SUCCESS] Destination Reached!")
                    break

                if elapsed > config.SIM_DURATION:
                    print("\n[TIMEOUT] Simulation ended.")
                    break

                sleep_time = config.DT - (time.time() - loop_start)
                if sleep_time > 0:
                    time.sleep(sleep_time)

    except KeyboardInterrupt:
        print("\n[STOP] Simulation stopped by user.")

    finally:
        plot_results(path_local, traj)

    print("==================================================")

def plot_results(path_local, traj):
    try:
        import matplotlib.pyplot as plt

        px = [p[0] for p in path_local]
        py = [p[1] for p in path_local]

        tx = [p[0] for p in traj]
        ty = [p[1] for p in traj]

        plt.figure(figsize=(12, 6))
        plt.plot(px, py, label="Planned Path", linewidth=2)
        plt.plot(tx, ty, label="Actual Trajectory", linestyle="--")
        plt.scatter([px[0]], [py[0]], label="Start")
        plt.scatter([px[-1]], [py[-1]], label="End")

        # Field boundary
        plt.plot([0, config.FIELD_LENGTH, config.FIELD_LENGTH, 0, 0],
                 [0, 0, config.FIELD_WIDTH, config.FIELD_WIDTH, 0],
                 linestyle="--", label="Field Boundary")

        plt.xlim(0, config.FIELD_LENGTH)
        plt.ylim(0, config.FIELD_WIDTH)
        plt.xlabel("X (m)")
        plt.ylabel("Y (m)")
        plt.title("Autonomous Tractor Path Tracking with Smooth U-Turns")
        plt.legend()
        plt.grid(True, linestyle="--", alpha=0.5)
        plt.tight_layout()
        plt.savefig("data/plot.png", dpi=150)
        plt.show()

        print("Visualization saved to data/plot.png")

    except Exception as e:
        print("[WARN] Plotting failed:", e)

if __name__ == "__main__":
    main()
